export const homePageInfo = [
  {
    'title': 'Banners',
    'key': 'banner',
    'list': [
      { 'content_id': 1001, 'publish_time': '2016', 'title': 'John Wick 3', 'orentitation': 0, 'duration': '40 minutes', 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': '', 'description': 'John Wick is on the run after killing a member of the international assassins guild, and with a $14 million price tag on his head, he is the target of hit men and women everywhere.' , 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1002, 'publish_time': '2019', 'title': 'The Handmaiden', 'orentitation': 0, 'duration': '90 minutes', 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': '', 'description': '', 'playback_url': '', 'tags': 'Thriller & Misdaad, Drama, Romantiek' }]
  },
  {
    'title': 'Movies',
    'key': 'movies',
    'list': [
      { 'content_id': 1008, 'description': 'A troubled security guard begins working at Freddy Fazbears Pizza During his first night on the job, he realizes that the night shift wont be so easy to get through. Pretty soon he will unveil what actually happened at Freddys','duration': '40 minutes', 'publish_time': '2019', 'title': 'FIVE NIGHTS AT FREDDYS' , 'orentitation': 1, 'banner_medium': 'cae23eedba1c8c08b57ebc9e893879c419f4d4e9.jpg', 'banner_image': 'banner.webp', 'poster_image': 'poster_4.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1009, 'description': 'The incredible true story of a former government agent turned vigilante who embarks on a dangerous mission to rescue hundreds of children from traffickers.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'SOUND OF FREEDOM', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_5.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1010, 'description': 'The history of the United States from the 1950s to the 70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Forrest Gump', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_6.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1011, 'description': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'PULP FICTION', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_7.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1012, 'description': 'An alien scarab chooses Jaime Reyes to be its symbiotic host, bestowing the recent college graduate with a suit of armor thats capable of extraordinary powers, forever changing his destiny as he becomes the superhero known as Blue Beetle.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Blue Beetle', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_8.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1013, 'description': 'During the 90s, a new faction of Transformers - the Maximals - join the Autobots as allies in the battle for Earth.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'TRANSFORMERS: RISE OF THE BEASTS', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_9.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1014, 'description': 'Barbie suffers a crisis that leads her to question her world and her existence.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Barbie', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_10.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1015, 'description': 'When two girls disappear into the woods and return three days later with no memory of what happened to them, the father of one girl seeks out Chris MacNeil, whos been forever altered by what happened to her daughter fifty years ago.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'THE EXORCIST BELIEVER', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_11.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1016, 'description': 'Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'FAST-X', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_12.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1017, 'description': 'Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends protector by taking on the mafia.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'THE Equalizer-3', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_13.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1018, 'description': 'A sick and desperate John travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer only to discover the entire operation is a scam to defraud the most vulnerable.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'SAW X', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_14.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1019, 'description': 'The adventures of a band of space warriors who work to protect the universe from the evil overlord Thanos.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Gardians of the Galaxy', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_1.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1020, 'description': 'Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'MISSION:IMPOSSIBLE Dead Reckoning -Part ONE', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_2.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1021, 'description': 'Armed with every weapon they can get their hands on, the Expendables are the worlds last line of defense and the team that gets called when all other options are off the table.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'EXPENDABLES-4', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_3.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1022, 'description': 'A troubled security guard begins working at Freddy Fazbears Pizza During his first night on the job, he realizes that the night shift wont be so easy to get through. Pretty soon he will unveil what actually happened at Freddys' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'FIVE NIGHTS AT FREDDYS', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_4.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1023, 'description': 'The incredible true story of a former government agent turned vigilante who embarks on a dangerous mission to rescue hundreds of children from traffickers.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'SOUND OF FREEDOM', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_5.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1024, 'description': 'The history of the United States from the 1950s to the 70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Forrest Gump', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_6.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1025, 'description': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'PULP FICTION', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_7.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' }
    ]
  },
  {
    'title': 'Comedy',
    'key': 'comedy',
    'list': [
      { 'content_id': 1026, 'description': 'An alien scarab chooses Jaime Reyes to be its symbiotic host, bestowing the recent college graduate with a suit of armor thats capable of extraordinary powers, forever changing his destiny as he becomes the superhero known as Blue Beetle.','duration': '40 minutes', 'publish_time': '2019', 'title': 'Blue Beetle', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_8.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1027, 'description': 'During the 90s, a new faction of Transformers - the Maximals - join the Autobots as allies in the battle for Earth.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'TRANSFORMERS: RISE OF THE BEASTS', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_9.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1028, 'description': 'Barbie suffers a crisis that leads her to question her world and her existence.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Barbie', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_10.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1029, 'description': 'When two girls disappear into the woods and return three days later with no memory of what happened to them, the father of one girl seeks out Chris MacNeil, whos been forever altered by what happened to her daughter fifty years ago.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'THE EXORCIST BELIEVER', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_11.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1030, 'description': 'Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'FAST-X', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_12.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1031, 'description': 'Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends protector by taking on the mafia.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'THE Equalizer-3', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_13.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1032, 'description': 'A sick and desperate John travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer only to discover the entire operation is a scam to defraud the most vulnerable.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'SAW X', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_14.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1033, 'description': 'The adventures of a band of space warriors who work to protect the universe from the evil overlord Thanos.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Gardians of the Galaxy', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_1.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1034, 'description': 'Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'MISSION:IMPOSSIBLE Dead Reckoning -Part ONE', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_2.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1035, 'description': 'Armed with every weapon they can get their hands on, the Expendables are the worlds last line of defense and the team that gets called when all other options are off the table.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'EXPENDABLES-4', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_3.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' }
    ]
  },
  {
    'title': 'News',
    'key': 'news',
    'list': [
      { 'content_id': 1003, 'description': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'publish_time': '2019', 'title': 'PULP FICTION', 'orentitation': 1, 'duration': '50 minutes', 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_7.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1004, 'description': 'An alien scarab chooses Jaime Reyes to be its symbiotic host, bestowing the recent college graduate with a suit of armor thats capable of extraordinary powers, forever changing his destiny as he becomes the superhero known as Blue Beetle.', 'publish_time': '2021', 'title': 'Blue Beetle', 'orentitation': 1, 'duration': '65 minutes', 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_8.webp', 'playback_url': '', 'tags': 'Action & Adventure,Sciencefiction' },
      { 'content_id': 1005, 'description': 'A troubled security guard begins working at Freddy Fazbears Pizza During his first night on the job, he realizes that the night shift wont be so easy to get through. Pretty soon he will unveil what actually happened at Freddys', 'publish_time': '2022', 'title': 'FIVE NIGHTS AT FREDDYS', 'orentitation': 1, 'duration': '30 minutes', 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_4.webp', 'playback_url': '', 'tags': 'Comedy,Drama' },
      { 'content_id': 1006, 'description': 'The incredible true story of a former government agent turned vigilante who embarks on a dangerous mission to rescue hundreds of children from traffickers.', 'publish_time': '2020', 'title': 'SOUND OF FREEDOM', 'orentitation': 1, 'duration': '80 minutes', 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_5.webp', 'playback_url': '', 'tags': 'Sci-Fi,Fantasy,Adventure' },
      { 'content_id': 1007, 'description': 'The history of the United States from the 1950s to the 70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.', 'publish_time': '2021', 'title': 'Forrest Gump', 'orentitation': 1, 'duration': '90 minutes', 'banner_medium': '', 'banner_image': 'banner.webp', 'poster_image': 'poster_6.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
    ]
  }
]

export const categories = [
    { 'content_id': 1, 'category_id': '01', 'title': 'Home', 'slug': 'home', 'icon': 'images/home.png', 'title_en': 'Home', },
    { 'content_id': 1, 'category_id': '01', 'title': 'Search', 'slug': 'search', 'icon': 'images/search.png', 'title_en': 'Search', },
    { 'content_id': 1, 'category_id': '01', 'title': 'Movies', 'slug': 'movies', 'icon': 'images/movies.png', 'title_en': 'Movies', },
    { 'content_id': 1, 'category_id': '01', 'title': 'Profile', 'slug': 'profile', 'icon': 'images/user.png', 'title_en': 'Profile', }
]
